language: java
jdk:
  - oraclejdk11

before_script:

before_install:

script:
  echo "skip test...."

after_success:
  - mvn -Dlog.console.close=true  clean generate-resources cobertura:cobertura coveralls:report

branches:
  only:
    - main
