# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches:
      - main
      - github_action_add
  pull_request:
    branches:
      - main
      - github_action_add

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'

    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Build with Maven
      run: mvn install -DskipTests=true -P coverage --no-transfer-progress cobertura:cobertura

    - name: codecov
      uses: codecov/codecov-action@v2.0.1
      with:
        #file: ./jacoco.xml
        #token: ${{secrets.CODECOV_TOKEN}}
        file: ${{ github.workspace }}/**/target/site/jacoco/jacoco.xml
        #name: codecov

    - name: Upload coverage to codecov
      run: curl -s https://codecov.io/bash | bash







