# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'

    - name: Build with Maven
      run: mvn -B test -P coverage --no-transfer-progress

    - name: npm install, make test-coverage
      run: |
        npm install
        make test-coverage

    - name: Coveralls
        # You may pin to the exact commit or the version.
        # uses: coverallsapp/github-action@9ba913c152ae4be1327bfb9085dc806cedb44057
      uses: coverallsapp/github-action@v1.1.0
      with:
        github-token: ${{secrets.github_token}}
        #path-to-lcov: ./cov/lcov.info
